name: kedro-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - ipython>=8.10
    - jupyterlab>=3.0
    - notebook
    - kedro~=0.19.8
    - kedro-mlflow~=0.13.1
    - kedro[jupyter]
    - kedro-datasets[pandas-csvdataset, pandas-exceldataset, pandas-parquetdataset, plotly-plotlydataset, plotly-jsondataset, matplotlib-matplotlibwriter]>=3.0
    - kedro-viz>=6.7.0
    - pytest-cov~=3.0
    - pytest-mock>=1.7.1, <2.0
    - pytest~=7.2
    - ruff~=0.1.8
    - scikit-learn~=1.5.1; python_version >= "3.9"
    - seaborn~=0.12.1